from fpdf import FPDF
import os

class InternRoadmapPDF(FPDF):
    def header(self):
        # Background color for header
        self.set_fill_color(15, 23, 42) # Dark navy secondary
        self.rect(0, 0, 210, 40, 'F')
        
        # Title
        self.set_font('Arial', 'B', 22)
        self.set_text_color(255, 255, 255)
        self.cell(0, 20, 'CRMS PROJECT ROADMAP', 0, 1, 'C')
        
        self.set_font('Arial', '', 12)
        self.cell(0, 0, 'Professional Task Tracker for Internship Phases', 0, 1, 'C')
        self.ln(25)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by CRMS Intelligence System', 0, 0, 'C')

    def chapter_title(self, title, phase_num):
        self.set_font('Arial', 'B', 16)
        self.set_fill_color(99, 102, 241) # Primery Indigo
        self.set_text_color(255, 255, 255)
        self.cell(0, 12, f' PHASE {phase_num}: {title}', 0, 1, 'L', True)
        self.ln(5)

    def chapter_body(self, tasks):
        # Table Header
        self.set_font('Arial', 'B', 10)
        self.set_fill_color(241, 245, 249)
        self.set_text_color(15, 23, 42)
        
        # Column widths
        w = [15, 50, 95, 30]
        headers = ["ID", "Task Name", "Detailed Description", "Status"]
        
        for i in range(len(headers)):
            self.cell(w[i], 10, headers[i], 1, 0, 'C', True)
        self.ln()
        
        # Table Body
        self.set_font('Arial', '', 9)
        self.set_text_color(30, 41, 59)
        
        for task in tasks:
            # Multi-cell for description to handle wrapping
            x = self.get_x()
            y = self.get_y()
            
            self.cell(w[0], 15, task[0], 1, 0, 'C')
            self.cell(w[1], 15, task[1], 1, 0, 'L')
            
            # For the description, we use multi_cell but need to calculate height
            current_y = self.get_y()
            current_x = self.get_x()
            self.multi_cell(w[2], 7.5, task[2], 1, 'L')
            
            # Reset position for the next cell in the same row
            self.set_xy(current_x + w[2], current_y)
            self.cell(w[3], 15, task[3], 1, 1, 'C')

        self.ln(10)

def generate_pdf():
    pdf = InternRoadmapPDF()
    pdf.add_page()
    
    # Phase 1
    pdf.chapter_title("The Foundation (Data Acquisition)", 1)
    phase1_tasks = [
        ["1.1", "PDF Parsing", "Integrate PyMuPDF & pdfplumber for robust text extraction.", "DONE"],
        ["1.2", "Section Classification", "Regex-based detection to split Resume into clean segments.", "IN-PROGRESS"],
        ["1.3", "Eligibility Filter", "Logic for strict HR criteria (CGPA, Branch, Batch).", "PENDING"],
        ["1.4", "Async Pipeline", "Setup Celery + Redis for high-volume background tasks.", "DONE"],
        ["1.5", "UI Dashboard", "Premium React UI with modern aesthetics (Century Gothic).", "DONE"],
    ]
    pdf.chapter_body(phase1_tasks)
    
    # Phase 2
    pdf.chapter_title("The Logic (Standardization & AI)", 2)
    phase2_tasks = [
        ["2.1", "Data Annotation", "Annotate resumes in Label Studio for fine-tuning our NER.", "PENDING"],
        ["2.2", "DistilBERT Model", "Train custom model for Skills, Projects, and Cert entities.", "PENDING"],
        ["2.3", "Skill Taxonomy", "Build hierarchical JSON map of software tech branches.", "DONE"],
        ["2.4", "Skill Normalizer", "Standardize abbreviations (e.g. 'JS' -> 'JavaScript').", "DONE"],
    ]
    pdf.chapter_body(phase2_tasks)
    
    # Phase 3
    pdf.chapter_title("The Intelligence (Semantic Matching)", 3)
    phase3_tasks = [
        ["3.1", "Semantic Embeddings", "Convert sections into 384-dim vectors with Sentence-BERT.", "IN-PROGRESS"],
        ["3.2", "Weighted Scorer", "Apply 6-dimension logic to output a calibrated match score.", "PENDING"],
        ["3.3", "Explainability", "Generate natural language reasoning for each candidate score.", "PENDING"],
        ["3.4", "HR Leaderboard", "Final ranking dashboard with filters and override controls.", "PENDING"],
    ]
    pdf.chapter_body(phase3_tasks)
    
    output_path = r"c:\Dev\CRMS_Resume\CRMS_Intern_Roadmap.pdf"
    pdf.output(output_path)
    print(f"PDF generated at: {output_path}")

if __name__ == "__main__":
    generate_pdf()
